name: Deploy Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    uses: valitydev/base-workflow/.github/workflows/maven-service-deploy.yml@b940f993928d6d75395621af90f7d42af2cf824c
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}}